// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechStore.Api.Modules.Catalog;

#nullable disable

namespace TechStore.Api.Modules.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechStore.Api.Modules.Catalog.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Products", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000001"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Notebook Dell com processador Intel Core i7, 16GB RAM, SSD 512GB",
                            Estoque = 25,
                            Nome = "Notebook Dell Inspiron 15",
                            Preco = 4299.99m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000002"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Apple MacBook Air com chip M2, 8GB RAM, SSD 256GB",
                            Estoque = 10,
                            Nome = "MacBook Air M2",
                            Preco = 7999.00m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000003"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000001"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Notebook Lenovo com Ryzen 5, 8GB RAM, SSD 256GB",
                            Estoque = 30,
                            Nome = "Lenovo IdeaPad 3",
                            Preco = 2899.00m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000004"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Teclado mecânico RGB, switches blue, layout ABNT2",
                            Estoque = 50,
                            Nome = "Teclado Mecânico Redragon Kumara",
                            Preco = 249.90m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000005"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Mouse gamer sem fio, sensor HERO, 12000 DPI",
                            Estoque = 40,
                            Nome = "Mouse Logitech G305",
                            Preco = 199.90m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000006"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000002"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Headset gamer com microfone, drivers 50mm",
                            Estoque = 35,
                            Nome = "Headset HyperX Cloud Stinger",
                            Preco = 299.00m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000007"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "NVIDIA GeForce RTX 4060 8GB GDDR6",
                            Estoque = 15,
                            Nome = "Placa de Vídeo RTX 4060",
                            Preco = 2199.00m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000008"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Processador AMD Ryzen 7, 8 cores, 16 threads, 4.7GHz",
                            Estoque = 20,
                            Nome = "Processador AMD Ryzen 7 5800X",
                            Preco = 1599.00m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000009"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000003"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "SSD NVMe M.2 1TB, leitura 3500MB/s",
                            Estoque = 60,
                            Nome = "SSD Kingston NV2 1TB",
                            Preco = 399.90m
                        },
                        new
                        {
                            Id = new Guid("b1b2c3d4-0002-0001-0001-000000000010"),
                            Ativo = true,
                            CategoriaId = new Guid("a1b2c3d4-0001-0001-0001-000000000004"),
                            DataCriacao = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descricao = "Monitor ultrawide 29 polegadas, IPS, 2560x1080, 75Hz",
                            Estoque = 12,
                            Nome = "Monitor LG UltraWide 29\"",
                            Preco = 1299.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
